export default {
  LOAD_ITEMS: "LOAD_ITEMS",
  SET_WEB_URL: "SET_WEB_URL",
  SET_LOADING: "SET_LOADING",
  SET_SAVING: "SET_SAVING",
  GET_CURRENT_MODE: "GET_CURRENT_MODE",
  SET_CURRENT_MODE: "SET_CURRENT_MODE",
  GET_CURRENT_LIST_ID: "GET_CURRENT_LIST_ID",
  GET_CURRENT_LISTITEM_ID: "GET_CURRENT_LISTITEM_ID",
  SET_FORM_FIELDS: "SET_FORM_FIELDS",
  UPDATE_FIELD_VALUE: "UPDATE_FIELD_VALUE",
  SET_PNP_CLIENT: "SET_PNP_CLIENT"
}